version: '3.7'

services:
  vault:
    image: vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    volumes:
      - ./vault-config:/vault/config
      - vault-data:/vault/file
    cap_add:
      - IPC_LOCK
    entrypoint: /vault/config/vault-startup.sh
    networks:
      - roar_net

  plex:
    image: binhex/arch-plex:latest
    container_name: plex
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /mnt/user/appdata/binhex-plex:/config
      - /mnt/user/rrr-data/media:/media
    ports:
      - 32400:32400
      - 1900:1900
    networks: 
      - roar_net
    restart: unless-stopped
    depends_on:
      - dnsmasq
      
  nzbget:
    image: binhex/arch-nzbget:latest
    container_name: nzbget
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /mnt/user/appdata/binhex-nzbget:/config
      - /mnt/user/rrr-data/usenet:/data/usenet
      - secrets:/vault/secrets
    ports:
      - 6789:6789
    networks:
      - roar_net
    restart: unless-stopped
    depends_on:
      - dnsmasq
      - vault

  vault-agent-nzbget:
    image: vault:latest
    container_name: vault-agent-nzbget
    volumes:
      - secrets:/vault/secrets
    environment:
      - VAULT_ADDR=http://vault:8200
    command: >
      vault agent -config=- <<EOF
      pid_file = "/tmp/pidfile"
      auto_auth {
        method "approle" {
          mount_path = "auth/approle"
          config = {
            role_id_file_path = "/vault/secrets/role_id"
            secret_id_file_path = "/vault/secrets/secret_id"
            remove_secret_id_file_after_read = "false"
          }
        }
      }
      template {
        source      = "/vault/secrets/nzbget.ctmpl"
        destination = "/vault/secrets/nzbget.env"
        command     = "sh -c 'kill -HUP $(cat /tmp/pidfile)'"
      }
      EOF
    depends_on:
      - vault
    networks:
      - roar_net

  prowlarr:
    image: binhex/arch-prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /mnt/user/appdata/binhex-prowlarr:/config
    ports:
      - 9696:9696
    networks:
      - roar_net
    restart: unless-stopped
    depends_on:
      - dnsmasq
      
  radarr:
    image: binhex/arch-radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /mnt/user/appdata/binhex-radarr:/config
      - /mnt/user/rrr-data:/data
    ports:
      - 7878:7878
    networks:
      - roar_net
    restart: unless-stopped
    depends_on:
      - nzbget
      - prowlarr
      - dnsmasq

  sonarr:
    image:  binhex/arch-sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /mnt/user/appdata/binhex-sonarr:/config
      - /mnt/user/rrr-data:/data
    ports:
      - 8989:8989
    networks:
      - roar_net
    restart: unless-stopped
    depends_on:
      - nzbget
      - prowlarr
      - dnsmasq

  overseerr:
    image:  binhex/arch-overseerr:latest
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /mnt/user/appdata/binhex-overseerr:/config
    ports:
      - 5055:5055
    networks:
      - roar_net
    restart: unless-stopped
    depends_on:
      - radarr
      - sonarr
      - dnsmasq

  dnsmasq:
    image: jpillora/dnsmasq
    container_name: dnsmasq
    restart: unless-stopped
    ports:
      - "53:53/udp"
    environment:
      - DNSMASQ_LOG=true
    volumes:
      - /mnt/user/appdata/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
    networks:
      - roar_net

volumes:
  vault-data:
  secrets:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      
networks:
  roar_net:
    driver: bridge
    