services:
  plex:
    image: binhex/arch-plex:latest
    container_name: plex
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /mnt/user/appdata/binhex-plex:/config
      - /mnt/user/rrr-data/media:/media
    ports:
      - 32400:32400
      - 1900:1900
    networks: 
      - roar_net
    restart: unless-stopped
    depends_on:
      - dnsmasq
      
  nzbget:
    image: binhex/arch-nzbget:latest
    container_name: nzbget
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /mnt/user/appdata/binhex-nzbget:/config
      - /mnt/user/rrr-data/usenet:/data/usenet
    ports:
      - 6789:6789
    networks:
      - roar_net
    restart: unless-stopped
    depends_on:
      - dnsmasq

  prowlarr:
    image: binhex/arch-prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /mnt/user/appdata/binhex-prowlarr:/config
    ports:
      - 9696:9696
    networks:
      - roar_net
    restart: unless-stopped
    depends_on:
      - dnsmasq
      
  radarr:
    image: binhex/arch-radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /mnt/user/appdata/binhex-radarr:/config
      - /mnt/user/rrr-data:/data
    ports:
      - 7878:7878
    networks:
      - roar_net
    restart: unless-stopped
    depends_on:
      - nzbget
      - prowlarr
      - dnsmasq

  sonarr:
    image:  binhex/arch-sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /mnt/user/appdata/binhex-sonarr:/config
      - /mnt/user/rrr-data:/data
    ports:
      - 8989:8989
    networks:
      - roar_net
    restart: unless-stopped
    depends_on:
      - nzbget
      - prowlarr
      - dnsmasq

  overseerr:
    image:  binhex/arch-overseerr:latest
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /mnt/user/appdata/binhex-overseerr:/config
    ports:
      - 5055:5055
    networks:
      - roar_net
    restart: unless-stopped
    depends_on:
      - radarr
      - sonarr
      - dnsmasq

  dnsmasq:
    image: jpillora/dnsmasq
    container_name: dnsmasq
    restart: unless-stopped
    ports:
      - "53:53/udp"
    environment:
      - DNSMASQ_LOG=true
    volumes:
      - /mnt/user/appdata/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
    networks:
      - roar_net
      
networks:
  roar_net:
    driver: bridge
    